### ISSUE TITLE
Template should include opportunity for shoutouts

### ISSUE THREAD

**Issue by ianjennings** [MLH-Fellowship/create-standup-discussions#2]
I don't see the `./.github/STANDUP_TEMPLATE.md` within the repository.

Markdown template should include the following:

```md
**Shoutouts**:
- @user for x
```

**Comment by theycallmeswift** [comment]
@ianjennings make a pull request in MLH-Fellowship/fellows-0 (https://github.com/MLH-Fellowship/fellows-0/blob/master/.github/STANDUP_TEMPLATE.md). I'll merge it for you!
